backend:
  name: git-gateway
  branch: prod

media_folder: static/img
public_folder: /img

collections:
  - name: "work"
    label: "Work"
    folder: "src/content/work"
    create: true
    slug: "work/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }